apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-extern
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitlab.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab-nginx-ingress-controller
            port:
              number: 80

